package CORBA_A2;


/**
* CORBA_A2/Functions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Functions.idl
* Saturday, October 17, 2020 12:23:06 o'clock PM EDT
*/

public interface Functions extends FunctionsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Functions
