package CORBA_A2;


/**
* CORBA_A2/FunctionsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Functions.idl
* Wednesday, October 14, 2020 4:36:29 o'clock PM EDT
*/

public interface FunctionsOperations 
{

  // manager
  String addItem (String managerID, String itemID, String itemName, String quantity, String price);
  String removeItem (String managerID, String itemID, String quantity);
  String listItemAvailability (String managerID);

  // customer
  String purchaseItem (String customerID, String itemID, String dateOfPurchase);
  String findItem (String customerID, String itemName);
  String returnItem (String customerID, String itemID, String dateOfReturn);
  String exchangeItem (String customerID, String newItemID, String oldItemID);
} // interface FunctionsOperations
