package CORBA_A2;


/**
* CORBA_A2/FunctionsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Functions.idl
* Saturday, October 17, 2020 12:23:06 o'clock PM EDT
*/

public abstract class FunctionsPOA extends org.omg.PortableServer.Servant
 implements CORBA_A2.FunctionsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("removeItem", new java.lang.Integer (1));
    _methods.put ("listItemAvailability", new java.lang.Integer (2));
    _methods.put ("purchaseItem", new java.lang.Integer (3));
    _methods.put ("findItem", new java.lang.Integer (4));
    _methods.put ("returnItem", new java.lang.Integer (5));
    _methods.put ("exchangeItem", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // manager
       case 0:  // CORBA_A2/Functions/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         String quantity = in.read_string ();
         String price = in.read_string ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity, price);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CORBA_A2/Functions/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String quantity = in.read_string ();
         String $result = null;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CORBA_A2/Functions/listItemAvailability
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // customer
       case 3:  // CORBA_A2/Functions/purchaseItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfPurchase = in.read_string ();
         String $result = null;
         $result = this.purchaseItem (customerID, itemID, dateOfPurchase);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CORBA_A2/Functions/findItem
       {
         String customerID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (customerID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // CORBA_A2/Functions/returnItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfReturn = in.read_string ();
         String $result = null;
         $result = this.returnItem (customerID, itemID, dateOfReturn);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // CORBA_A2/Functions/exchangeItem
       {
         String customerID = in.read_string ();
         String newItemID = in.read_string ();
         String oldItemID = in.read_string ();
         String dateofReturn = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (customerID, newItemID, oldItemID, dateofReturn);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBA_A2/Functions:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Functions _this() 
  {
    return FunctionsHelper.narrow(
    super._this_object());
  }

  public Functions _this(org.omg.CORBA.ORB orb) 
  {
    return FunctionsHelper.narrow(
    super._this_object(orb));
  }


} // class FunctionsPOA
