package CORBA_A2;

/**
* CORBA_A2/FunctionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Functions.idl
* Saturday, October 17, 2020 12:23:06 o'clock PM EDT
*/

public final class FunctionsHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA_A2.Functions value = null;

  public FunctionsHolder ()
  {
  }

  public FunctionsHolder (CORBA_A2.Functions initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA_A2.FunctionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA_A2.FunctionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA_A2.FunctionsHelper.type ();
  }

}
